# Generated by Django 5.1.3 on 2024-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'This username already exists.'}, help_text='This field is required.', max_length=20, unique=True)),
                ('password', models.CharField(help_text='This field is required.', max_length=255)),
            ],
        ),
    ]
