# Generated by Django 5.1.3 on 2025-01-09 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contentblock_delete_createcontentblock_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='content/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
