# Generated by Django 5.1.3 on 2025-01-09 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contentblock_delete_createcontentblock_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='image',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='content/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
